name: Deploy to GitHub Pages (Angular)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # Build using Angular CLI provided by npx (-p installs it temporarily)
      - name: Build Angular (Project Page)
        run: npx -p @angular/cli@^17 ng build --configuration=production --base-href "/<amanda-repository>/" --output-path dist

      - name: Resolve dist path
        id: dist
        shell: bash
        run: |
          set -e
          if compgen -G "dist/*/index.html" > /dev/null; then
            DIST_DIR="$(dirname "$(ls dist/*/index.html | head -n1)")"
          elif [ -f dist/index.html ]; then
            DIST_DIR="dist"
          else
            echo "No build output found in dist/"
            exit 1
          fi
          echo "dist_path=$DIST_DIR" >> "$GITHUB_OUTPUT"
          echo "Resolved dist path: $DIST_DIR"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4