name: Deploy to GitHub Pages (Angular 19)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: package-lock.json

      - run: npm pkg set "overrides.zone.js=~0.15.1"
      - run: npm ci

      # Build for custom domain (served from root)
      - name: Build Angular
        run: npx ng build --configuration production --base-href "/"

      # Find the browser output folder (SSR -> /browser, SPA -> root)
      - name: Locate Angular output
        id: out
        run: |
          set -e
          if [ -d "dist/amanda-portfolio/browser" ]; then
            echo "dir=dist/amanda-portfolio/browser" >> $GITHUB_OUTPUT
          elif [ -d "dist/amanda-portfolio" ]; then
            echo "dir=dist/amanda-portfolio" >> $GITHUB_OUTPUT
          else
            FILE=$(find dist -type f -name index.html | head -n 1 || true)
            if [ -z "$FILE" ]; then
              echo "No index.html found under dist/"; exit 1
            fi
            echo "dir=$(dirname "$FILE")" >> $GITHUB_OUTPUT
          fi
          echo "Using output dir: $(cat $GITHUB_OUTPUT)"

      # Stage everything we want to publish
      - name: Prepare publish folder
        run: |
          rm -rf publish
          mkdir -p publish
          rsync -av --delete "${{ steps.out.outputs.dir }}/" publish/
          cp publish/index.html publish/404.html
          echo "www.amandarae.dev" > publish/CNAME
          echo "Publish file count: $(find publish -type f | wc -l)"
          echo "Top-level files:"; find publish -maxdepth 1 -type f -print

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
